import js from '@eslint/js';

export default [
  js.configs.recommended,

  // Global ignores
  {
    ignores: [
      'lib/**',
      'node_modules/**',
      'dist/**',
      'src/lib/*.ts',
      'vite.config.js',
    ],
  },

  // Main game files
  {
    files: ['*.js', 'js/**/*.js', 'js/jsx/**/*.jsx', 'src/**/*.js'],
    languageOptions: {
      ecmaVersion: 5,
      sourceType: 'script',
      globals: {
        // Dojo
        dojo: 'readonly',
        // React (provided by our module setup)
        React: 'readonly',
        // Libs
        Dropbox: 'readonly',
        $: 'readonly',
        jQuery: 'readonly',
        LCstorage: 'readonly',
        LZString: 'readonly',
        md5: 'readonly',
        // i18n
        $I: 'writable',
        i18nLang: 'writable',
        // UI globals
        UIUtils: 'writable',
        ButtonModernHelper: 'writable',
        // Namespaces (set by dojo.declare)
        com: 'readonly',
        classes: 'readonly',
        mixin: 'readonly',
        // JSX component globals (assigned from module side-effects)
        WCollapsiblePanel: 'writable',
        WResourceRow: 'writable',
        WCraftRow: 'writable',
        WResourceTable: 'writable',
        WCraftTable: 'writable',
        WLeftPanel: 'writable',
        WPins: 'writable',
        WTooltip: 'writable',
        WCraftShortcut: 'writable',
        WMidPanel: 'writable',
        WToolbar: 'writable',
        WToolbarIconContainer: 'writable',
        WToolbarHappiness: 'writable',
        WToolbarEnergy: 'writable',
        WToolbarMOTD: 'writable',
        WToolbarPollution: 'writable',
        WToolbarFPS: 'writable',
        WBLS: 'writable',
        WLoginForm: 'writable',
        WCloudSaveRecord: 'writable',
        WCloudSaves: 'writable',
        WLogin: 'writable',
        WQueueItem: 'writable',
        WQueue: 'writable',
        WTerminal: 'writable',
        WChiral: 'writable',
        // Config
        config: 'readonly',
        $r: 'readonly',
        // Browser
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        newrelic: 'writable',
        NREUM: 'writable',
        navigator: 'readonly',
        location: 'readonly',
        JSON: 'readonly',
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        // Game runtime
        game: 'writable',
        gamePage: 'writable',
        gtag: 'writable',
      },
    },
    rules: {
      'quotes': ['warn', 'double'],
      'semi': ['error', 'always'],
      'no-mixed-spaces-and-tabs': ['warn', 'smart-tabs'],
      'no-unused-vars': 'warn',
      'no-prototype-builtins': 'warn',
      'space-infix-ops': 'warn',
      'no-redeclare': 'off',
      'curly': 'error',
    },
  },

  // Test files (ES6+)
  {
    files: ['test/**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'module',
      globals: {
        vi: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        describe: 'readonly',
        global: 'readonly',
        require: 'readonly',
        process: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        // Game globals
        com: 'readonly',
        classes: 'readonly',
        mixin: 'readonly',
        dojo: 'readonly',
        $: 'readonly',
        LZString: 'readonly',
        LCstorage: 'readonly',
        $I: 'readonly',
        game: 'writable',
        gamePage: 'writable',
        React: 'readonly',
        console: 'readonly',
        jest: 'readonly',
        // Browser APIs (jsdom)
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        XMLHttpRequest: 'readonly',
        Promise: 'readonly',
        JSON: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Array: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        Error: 'readonly',
        Object: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        Symbol: 'readonly',
        RegExp: 'readonly',
        Function: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'off',
    },
  },
];
